#!/usr/bin/env python
# encoding: utf8

import sys
import time

import rospy
import smach
import smach_ros

import rcprg_smach.conversation
import rcprg_smach.clean

# import rcprg_kb.places_xml as kb_p
import tiago_kb.places_xml as kb_p


from rcprg_smach.task_manager import PoseDescription

from pl_nouns.dictionary_client import DisctionaryServiceClient

from TaskER.TaskER import TaskER
from TaskER.dynamic_agent import DynAgent
from tasker_msgs.msg import RobotResource, ScheduleParams
from tasker_msgs.srv import SuspendConditionsRequest, SuspendConditionsResponse
from tasker_msgs.srv import CostConditionsRequest, CostConditionsResponse
# for ExeSuspension state
import subprocess
import imp

RUNIntrospectionServer = True

def ptf_csp(ptf_id):
    flag = None
    if ptf_id[0] == "scheduleParams":
        return [flag, ScheduleParams(cost = 10, completion_time=1,cost_per_sec=1,final_resource_state=RobotResource())]
    elif ptf_id[0] == "suspendCondition":
        req = SuspendConditionsRequest()
        req = ptf_id[1]
        return [flag, SuspendConditionsResponse(cost_per_sec=1, cost_to_resume=1)]
    elif ptf_id[0] == "startCondition":
        req = CostConditionsRequest()
        req = ptf_id[1]
        return [flag, CostConditionsResponse(cost_per_sec=1, cost_to_complete=1)]

class MyTaskER(TaskER):
    def __init__(self, da_state_name, da_name, task_kb_id):
        self.name = unicode(da_name)

        # ROS node init
        rospy.init_node(self.name)
        self.sim_mode = None
        self.conversation_interface = None
        self.kb_places = None
        self.task_kb_id = task_kb_id

        # execution of TaskER init
        # SMACH SM is created
        TaskER.__init__(self,da_state_name)

        # execution of SMACH visualisation server
        if RUNIntrospectionServer:
            self.sis = smach_ros.IntrospectionServer(unicode(str("/"+self.name+"smach_view_server")), self, unicode(self.name))
            self.sis.start()

        # fetching of places parameteres
        # fetching of execution mode (sim, real, gazebo)
        places_xml_filename = rospy.get_param('/kb_places_xml')
        self.sim_mode = str(rospy.get_param('/sim_mode'))
        assert self.sim_mode in ['sim', 'gazebo', 'real']

        # print 'Reading KB for places from file "' + places_xml_filename + '"'
        self.kb_places = kb_p.PlacesXmlParser(places_xml_filename).getKB()
        if len(sys.argv) < 3:
            raise Exception('Too few arguments: ' + str(sys.argv))

        # assigning of place given in the execution command to var place_name
        m1_place_name = None
        m2_place_name = None
        m3_place_name = None
        for idx in range(1, len(sys.argv), 2):
            if sys.argv[idx] == 'm1':
                m1_place_name = sys.argv[idx+1] 
            if sys.argv[idx] == 'm2':
                m2_place_name = sys.argv[idx+1] 
            if sys.argv[idx] == 'm3':
                m3_place_name = sys.argv[idx+1] 
        self.places_names = [m1_place_name, m2_place_name, m3_place_name]
        
        # STATE MACHINE EXECUTION HAPPENS IN SWAP_STATE, BEFORE STATES ARE CREATED, INIT 
        # FUNCTIONS ARE EXECUTED, BUT NO "SMACH FLOW", WHICH IS TRANSITION FUNCTIONS 
        # EXECUTIONS AND TRANFERS BETWEEN STATES IS DONE
        self.swap_state('ExecFSM', rcprg_smach.clean.Clean(self.sim_mode, self.conversation_interface, self.kb_places, self.task_kb_id, self.places_names))
        
    def shutdownRequest(self):
        print ("my-tasker -----------------------   shutdown")
        # self.conversation_interface.stop()
        if RUNIntrospectionServer:
            self.sis.stop()
            self.sis.clear()
        
    def cleanup_tf(self):
        rospy.loginfo('{}: Executing state: {}'.format(rospy.get_name(), self.__class__.__name__))
        print 'Cleanup.execute'
        # self.conversation_interface.stop()
        print("CLEANUP EXECUTED")
        return 'ok'

    def get_suspension_tf(self,susp_data):
        print "My TASKER -- get_suspension_tf"
        print "My TASKER"
        print "My TASKER"
        rospy.loginfo('{}: Executing state: {}'.format(rospy.get_name(), self.__class__.__name__))
        print 'GetSuspend.execute'
        print "susp data: ", susp_data.getData()
        print "susp data[0]: ", susp_data.getData()[0]
        data = susp_data.getData()
        fsm_executable = None

        # print("IN GET SUSPENSION TF IN CLEAN TASK")
        # print("DATA")
        # for d in data:
        #     print("d")
        #     print(d)

        # for idx in range(2, len(data), 2):
        #     # print data[idx]
        #     if data[idx] == 'executable':
        #         fsm_executable = data[idx+1]
        #     elif data[idx] == 'rosrun':
        #         ros_pkg = data[idx+1]
        #         ros_exec = data[idx+2]
        #         fsm_executable = "rosrun "+ros_pkg+" "+ros_exec
        fsm_executable = "clean"

        if fsm_executable == None:
            print "harmoniser did not specified executable for suspension behaviour, terminating task"
            fsm_executable = "terminate task"
        
        return fsm_executable

    def exe_suspension_tf(self,fsm_es_in):
        print "My TASKER -- exe_suspension_tf"
        print "My TASKER"
        print "My TASKER"
        rospy.loginfo('{}: Executing state: {}'.format(rospy.get_name(), self.__class__.__name__))
        print 'ExecSuspension.execute'
        #srv.shutdown()
        print fsm_es_in
        if fsm_es_in == "terminate task":
            return 'shutdown'
        else:
            p = subprocess.Popen(fsm_es_in , shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

            # and you can block util the cmd execute finish
            p.wait()
        return 'FINISHED'
    def wait_tf(self):
        # print "My TASKER -- wait_tf"
        # print "My TASKER"
        # print "My TASKER"
        pass
    def update_task_tf(self):
        print("UPDATING TF CLEAN")
        print "My TASKER -- update_task_tf"
        print "My TASKER"
        print "My TASKER"
        if RUNIntrospectionServer:
            self.sis.stop()
            self.sis.clear()

        self.swap_state('ExecFSM', rcprg_smach.clean.Clean(self.sim_mode, self.conversation_interface, self.kb_places, self.task_kb_id, self.places_names))
        
        pass
    def initialise_tf(self):
        print "My TASKER -- initialise"

        # wykomentowane bo nie dano zadnego conversation_interface i powodowalo bledy (None type has no method start()) 
        # self.conversation_interface.start()

def main():
    da_name = None
    da_type = None
    da_id = None
    task_kb_id = None
    da_state_name = []
    for idx in range(1, len(sys.argv), 2):
        if sys.argv[idx] == 'da_name':
            da_name = sys.argv[idx+1]
        if sys.argv[idx] == 'da_type':
            da_type = sys.argv[idx+1]
        if sys.argv[idx] == 'da_id':
            da_id = sys.argv[idx+1]
        if sys.argv[idx] == 'task_kb_id':
            task_kb_id = sys.argv[idx+1]
    if da_name == None or da_type == None or da_id == None or task_kb_id == None:
        print "DA: one of the parameters (<da_name>, <da_type>, <da_id>, or <task_kb_id>) is not specified"
        return 1

    da = DynAgent( da_name, da_id, da_type, ptf_csp, da_state_name, task_kb_id )
    da.run( MyTaskER(da_state_name,da_name,da_id) )
    return 0

if __name__ == '__main__':
    main()
    # print "ALLLLLLL CLOOOOOSSSSEEEEED"
    print "Clean task closed."
